import {
  BACKEND_API_ENDPOINT,
  COGNITO_IDENTITY_POOL_ID,
  AWS_REGION,
  COGNITO_USER_POOL_ID,
  COGNITO_USER_POOL_WEB_CLIENT_ID,
  USER_FILES_S3_BUCKET,
  ONESIGNAL_APP_ID,
  SLACK_WEB_HOOK_URL,
  AMPLITUDE_API_KEY,
  DEBUG_MODE,
  TERRA_DEV_ID,
  TERRA_API_KEY
} from '@env';

export type ConfigType = {
  BACKEND_API_ENDPOINT: string;
  COGNITO_IDENTITY_POOL_ID: string;
  AWS_REGION: string;
  COGNITO_USER_POOL_ID: string;
  COGNITO_USER_POOL_WEB_CLIENT_ID: string;
  USER_FILES_S3_BUCKET: string;
  ONESIGNAL_APP_ID: string;
  SLACK_WEB_HOOK_URL: string;
  AMPLITUDE_API_KEY: string;
  DEBUG_MODE: boolean;
  TERRA_DEV_ID: string;
  TERRA_API_KEY: string;
};

export const Config: ConfigType = {
  BACKEND_API_ENDPOINT: BACKEND_API_ENDPOINT || '',
  COGNITO_IDENTITY_POOL_ID: COGNITO_IDENTITY_POOL_ID || '',
  AWS_REGION: AWS_REGION || '',
  COGNITO_USER_POOL_ID: COGNITO_USER_POOL_ID || '',
  COGNITO_USER_POOL_WEB_CLIENT_ID: COGNITO_USER_POOL_WEB_CLIENT_ID || '',
  USER_FILES_S3_BUCKET: USER_FILES_S3_BUCKET || '',
  ONESIGNAL_APP_ID: ONESIGNAL_APP_ID || '',
  SLACK_WEB_HOOK_URL: SLACK_WEB_HOOK_URL || '',
  AMPLITUDE_API_KEY: AMPLITUDE_API_KEY || '',
  DEBUG_MODE: DEBUG_MODE === 'true' ? true : false,
  TERRA_DEV_ID: TERRA_DEV_ID || '',
  TERRA_API_KEY: TERRA_API_KEY || ''
};
